describe('Basic calculator', () => {
    beforeEach(() => {
        cy.visit('https://testsheepnz.github.io/BasicCalculator')
        cy.contains('Selenium Object')
    })
    afterEach(() => {
        cy.get('#clearButton').click()
    })
    it('PROTOTYPE | SUDĖTIS 7+4 ', () => {
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '11')
    })
    it('PROTOTYPE | ATIMTIS 7-4', () => {
        cy.get('#selectOperationDropdown').select('1').should('have.value', '1')
        cy.get('#selectOperationDropdown').should('have.value', '1')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '3')
    })
    it('PROTOTYPE | DAUGYBA 7*4', () => {
        cy.get('#selectOperationDropdown').select('2').should('have.value', '2')
        cy.get('#selectOperationDropdown').should('have.value', '2')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '28')
    })
    it('PROTOTYPE | DALYBA 7/4', () => {
        cy.get('#selectOperationDropdown').select('3').should('have.value', '3')
        cy.get('#selectOperationDropdown').should('have.value', '3')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '1.75')
    })
    it('PROTOTYPE | SULIPDYMAS 7&4', () => {
        cy.get('#selectOperationDropdown').select('4').should('have.value', '4')
        cy.get('#selectOperationDropdown').should('have.value', '4')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '74')
    })
    it('BUILD 1 | SUDĖTIS 7+4', () => {
        cy.get('#selectBuild').select('1').should('have.value', '1')
        cy.get('#selectBuild').should('have.value', '1')
        cy.get('#selectOperationDropdown').select('0').should('have.value', '0')
        cy.get('#selectOperationDropdown').should('have.value', '0')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '11')
    })
    it('BUILD 1 | ATIMTIS 7-4', () => {
        cy.get('#selectBuild').select('1').should('have.value', '1')
        cy.get('#selectBuild').should('have.value', '1')
        cy.get('#selectOperationDropdown').select('1').should('have.value', '1')
        cy.get('#selectOperationDropdown').should('have.value', '1')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '3')
    })
    it('BUILD 1 | DAUGYBA 7*4', () => {
        cy.get('#selectBuild').select('1').should('have.value', '1')
        cy.get('#selectBuild').should('have.value', '1')
        cy.get('#selectOperationDropdown').select('2').should('have.value', '2')
        cy.get('#selectOperationDropdown').should('have.value', '2')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '28')
    })
    it('BUILD 1 | DALYBA 7/4', () => {
        cy.get('#selectBuild').select('1').should('have.value', '1')
        cy.get('#selectBuild').should('have.value', '1')
        cy.get('#selectOperationDropdown').select('3').should('have.value', '3')
        cy.get('#selectOperationDropdown').should('have.value', '3')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '1.75')
    })
    it('BUILD 1 | SULIPDYMAS 7&4', () => {
        cy.get('#selectBuild').select('1').should('have.value', '1')
        cy.get('#selectBuild').should('have.value', '1')
        cy.get('#selectOperationDropdown').select('4').should('have.value', '4')
        cy.get('#selectOperationDropdown').should('have.value', '4')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '74')
    })
    it('BUILD 2 | SUDĖTIS 7+4', () => {
        cy.get('#selectBuild').select('2').should('have.value', '2')
        cy.get('#selectBuild').should('have.value', '2')
        cy.get('#selectOperationDropdown').select('0').should('have.value', '0')
        cy.get('#selectOperationDropdown').should('have.value', '0')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '11')
        //Detected bug: instead of Adding system Concatenates variables
    })
    it('BUILD 2 | ATIMTIS 7-4', () => {
        cy.get('#selectBuild').select('2').should('have.value', '2')
        cy.get('#selectBuild').should('have.value', '2')
        cy.get('#selectOperationDropdown').select('1').should('have.value', '1')
        cy.get('#selectOperationDropdown').should('have.value', '1')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '3')
    })
    it('BUILD 2 | DAUGYBA 7*4', () => {
        cy.get('#selectBuild').select('2').should('have.value', '2')
        cy.get('#selectBuild').should('have.value', '2')
        cy.get('#selectOperationDropdown').select('2').should('have.value', '2')
        cy.get('#selectOperationDropdown').should('have.value', '2')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '28')
    })
    it('BUILD 2 | DALYBA 7/4', () => {
        cy.get('#selectBuild').select('2').should('have.value', '2')
        cy.get('#selectBuild').should('have.value', '2')
        cy.get('#selectOperationDropdown').select('3').should('have.value', '3')
        cy.get('#selectOperationDropdown').should('have.value', '3')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '1.75')
    })
    it('BUILD 2 | SULIPDYMAS 7&4', () => {
        cy.get('#selectBuild').select('2').should('have.value', '2')
        cy.get('#selectBuild').should('have.value', '2')
        cy.get('#selectOperationDropdown').select('4').should('have.value', '4')
        cy.get('#selectOperationDropdown').should('have.value', '4')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '74')
        //Detected bug: Instead of Concatenating system Adds the variables
    })
    it('BUILD 3 | SUDĖTIS 7+4', () => {
        cy.get('#selectBuild').select('3').should('have.value', '3')
        cy.get('#selectBuild').should('have.value', '3')
        cy.get('#selectOperationDropdown').select('0').should('have.value', '0')
        cy.get('#selectOperationDropdown').should('have.value', '0')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '11')
    })
    it('BUILD 3 | ATIMTIS 7-4', () => {
        cy.get('#selectBuild').select('3').should('have.value', '3')
        cy.get('#selectBuild').should('have.value', '3')
        cy.get('#selectOperationDropdown').select('1').should('have.value', '1')
        cy.get('#selectOperationDropdown').should('have.value', '1')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '3')
    })
    it('BUILD 3 | DAUGYBA 7*4', () => {
        cy.get('#selectBuild').select('3').should('have.value', '3')
        cy.get('#selectBuild').should('have.value', '3')
        cy.get('#selectOperationDropdown').select('2').should('have.value', '2')
        cy.get('#selectOperationDropdown').should('have.value', '2')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '28')
    })
    it('BUILD 3 | DALYBA 7/4', () => {
        cy.get('#selectBuild').select('3').should('have.value', '3')
        cy.get('#selectBuild').should('have.value', '3')
        cy.get('#selectOperationDropdown').select('3').should('have.value', '3')
        cy.get('#selectOperationDropdown').should('have.value', '3')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '1.75')
    })
    it('BUILD 3 | SULIPDYMAS 7&4', () => {
        cy.get('#selectBuild').select('3').should('have.value', '3')
        cy.get('#selectBuild').should('have.value', '3')
        cy.get('#selectOperationDropdown').select('4').should('have.value', '4')
        cy.get('#selectOperationDropdown').should('have.value', '4')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '74')
    })
    it('BUILD 4 | SUDĖTIS 7+4', () => {
        cy.get('#selectBuild').select('4').should('have.value', '4')
        cy.get('#selectBuild').should('have.value', '4')
        cy.get('#selectOperationDropdown').select('0').should('have.value', '0')
        cy.get('#selectOperationDropdown').should('have.value', '0')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '11')
    })
    it('BUILD 4 | ATIMTIS 7-4', () => {
        cy.get('#selectBuild').select('4').should('have.value', '4')
        cy.get('#selectBuild').should('have.value', '4')
        cy.get('#selectOperationDropdown').select('1').should('have.value', '1')
        cy.get('#selectOperationDropdown').should('have.value', '1')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '3')
    })
    it('BUILD 4 | DAUGYBA 7*4', () => {
        cy.get('#selectBuild').select('4').should('have.value', '4')
        cy.get('#selectBuild').should('have.value', '4')
        cy.get('#selectOperationDropdown').select('2').should('have.value', '2')
        cy.get('#selectOperationDropdown').should('have.value', '2')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '28')
    })
    it('BUILD 4 | DALYBA 7/4', () => {
        cy.get('#selectBuild').select('4').should('have.value', '4')
        cy.get('#selectBuild').should('have.value', '4')
        cy.get('#selectOperationDropdown').select('3').should('have.value', '3')
        cy.get('#selectOperationDropdown').should('have.value', '3')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#integerSelect').click() //BUG: system does not let user remove 'Integers only' option
        cy.get('#numberAnswerField').should('have.value', '1.75') //BUG: Integers only option is automatically selected by the system
    })
    it('BUILD 4 | SULIPDYMAS 7&4', () => {
        cy.get('#selectBuild').select('4').should('have.value', '4')
        cy.get('#selectBuild').should('have.value', '4')
        cy.get('#selectOperationDropdown').select('4').should('have.value', '4')
        cy.get('#selectOperationDropdown').should('have.value', '4')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '74')
    })
    it('BUILD 5 | SUDĖTIS 7+4', () => {
        cy.get('#selectBuild').select('5').should('have.value', '5')
        cy.get('#selectBuild').should('have.value', '5')
        cy.get('#selectOperationDropdown').select('0').should('have.value', '0')
        cy.get('#selectOperationDropdown').should('have.value', '0')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '11')
    })
    it('BUILD 5 | ATIMTIS 7-4', () => {
        cy.get('#selectBuild').select('5').should('have.value', '5')
        cy.get('#selectBuild').should('have.value', '5')
        cy.get('#selectOperationDropdown').select('1').should('have.value', '1')
        cy.get('#selectOperationDropdown').should('have.value', '1')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '3')
    })
    it('BUILD 5 | DAUGYBA 7*4', () => {
        cy.get('#selectBuild').select('5').should('have.value', '5')
        cy.get('#selectBuild').should('have.value', '5')
        cy.get('#selectOperationDropdown').select('2').should('have.value', '2')
        cy.get('#selectOperationDropdown').should('have.value', '2')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '28')
    })
    it('BUILD 5 | DALYBA 7/4', () => {
        cy.get('#selectBuild').select('5').should('have.value', '5')
        cy.get('#selectBuild').should('have.value', '5')
        cy.get('#selectOperationDropdown').select('3').should('have.value', '3')
        cy.get('#selectOperationDropdown').should('have.value', '3')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '1.75')
    })
    it('BUILD 5 | SULIPDYMAS 7&4', () => {
        cy.get('#selectBuild').select('5').should('have.value', '5')
        cy.get('#selectBuild').should('have.value', '5')
        cy.get('#selectOperationDropdown').select('4').should('have.value', '4')
        cy.get('#selectOperationDropdown').should('have.value', '4')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '74')
    })
    it('BUILD 6 | SUDĖTIS 7+4', () => {
        cy.get('#selectBuild').select('6').should('have.value', '6')
        cy.get('#selectBuild').should('have.value', '6')
        cy.get('#selectOperationDropdown').select('0').should('have.value', '0')
        cy.get('#selectOperationDropdown').should('have.value', '0')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '11')
    })
    it('BUILD 6 | ATIMTIS 7-4', () => {
        cy.get('#selectBuild').select('6').should('have.value', '6')
        cy.get('#selectBuild').should('have.value', '6')
        cy.get('#selectOperationDropdown').select('1').should('have.value', '1')
        cy.get('#selectOperationDropdown').should('have.value', '1')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '3')
    })
    it('BUILD 6 | DAUGYBA 7*4', () => {
        cy.get('#selectBuild').select('6').should('have.value', '6')
        cy.get('#selectBuild').should('have.value', '6')
        cy.get('#selectOperationDropdown').select('2').should('have.value', '2')
        cy.get('#selectOperationDropdown').should('have.value', '2')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '28')
    })
    it('BUILD 6 | DALYBA 7/4', () => {
        cy.get('#selectBuild').select('6').should('have.value', '6')
        cy.get('#selectBuild').should('have.value', '6')
        cy.get('#selectOperationDropdown').select('3').should('have.value', '3')
        cy.get('#selectOperationDropdown').should('have.value', '3')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '1.75')
    })
    it('BUILD 6 | SULIPDYMAS 7&4', () => {
        cy.get('#selectBuild').select('6').should('have.value', '6')
        cy.get('#selectBuild').should('have.value', '6')
        cy.get('#selectOperationDropdown').select('4').should('have.value', '4')
        cy.get('#selectOperationDropdown').should('have.value', '4')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '74')
    })
    it('BUILD 7 | SUDĖTIS A+4', () => {
        cy.get('#selectBuild').select('7').should('have.value', '7')
        cy.get('#selectBuild').should('have.value', '7')
        cy.get('#selectOperationDropdown').select('0').should('have.value', '0')
        cy.get('#selectOperationDropdown').should('have.value', '0')
        cy.get('#number1Field').type('A')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.contains('Number 1 is not a number') //BUG
    })
    it('BUILD 7 | ATIMTIS A-4', () => {
        cy.get('#selectBuild').select('7').should('have.value', '7')
        cy.get('#selectBuild').should('have.value', '7')
        cy.get('#selectOperationDropdown').select('1').should('have.value', '1')
        cy.get('#selectOperationDropdown').should('have.value', '1')
        cy.get('#number1Field').type('A')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.contains('Number 1 is not a number') //BUG
    })
    it('BUILD 7 | DAUGYBA A*4', () => {
        cy.get('#selectBuild').select('7').should('have.value', '7')
        cy.get('#selectBuild').should('have.value', '7')
        cy.get('#selectOperationDropdown').select('2').should('have.value', '2')
        cy.get('#selectOperationDropdown').should('have.value', '2')
        cy.get('#number1Field').type('A')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.contains('Number 1 is not a number') //BUG
    })
    it('BUILD 7 | DALYBA A/4', () => {
        cy.get('#selectBuild').select('7').should('have.value', '7')
        cy.get('#selectBuild').should('have.value', '7')
        cy.get('#selectOperationDropdown').select('3').should('have.value', '3')
        cy.get('#selectOperationDropdown').should('have.value', '3')
        cy.get('#number1Field').type('A')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.contains('Number 1 is not a number') //BUG
    })
    it('BUILD 7 | SULIPDYMAS A&4', () => {
        cy.get('#selectBuild').select('7').should('have.value', '7')
        cy.get('#selectBuild').should('have.value', '7')
        cy.get('#selectOperationDropdown').select('4').should('have.value', '4')
        cy.get('#selectOperationDropdown').should('have.value', '4')
        cy.get('#number1Field').type('A')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', 'A4') //BUG: leidžią įvesti tiek raidines reikšmes, atsakymai yra gaunami random ir neteisingi
    })
    it('BUILD 8 | SUDĖTIS 7+4', () => {
        cy.get('#selectBuild').select('8').should('have.value', '8')
        cy.get('#selectBuild').should('have.value', '8')
        cy.get('#selectOperationDropdown').select('0').should('have.value', '0')
        cy.get('#selectOperationDropdown').should('have.value', '0')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '11')
    })
    it('BUILD 8 | ATIMTIS 7-4', () => {
        cy.get('#selectBuild').select('8').should('have.value', '8')
        cy.get('#selectBuild').should('have.value', '8')
        cy.get('#selectOperationDropdown').select('1').should('have.value', '1')
        cy.get('#selectOperationDropdown').should('have.value', '1')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '3') //BUG: Iš atsakymo matoma, kad kintamųjų reikšmės buvo apkeistos vietomis
    })
    it('BUILD 8 | DAUGYBA 7*4', () => {
        cy.get('#selectBuild').select('8').should('have.value', '8')
        cy.get('#selectBuild').should('have.value', '8')
        cy.get('#selectOperationDropdown').select('2').should('have.value', '2')
        cy.get('#selectOperationDropdown').should('have.value', '2')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '28')
    })
    it('BUILD 8 | DALYBA 7/4', () => {
        cy.get('#selectBuild').select('8').should('have.value', '8')
        cy.get('#selectBuild').should('have.value', '8')
        cy.get('#selectOperationDropdown').select('3').should('have.value', '3')
        cy.get('#selectOperationDropdown').should('have.value', '3')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '1.75') //BUG: Iš atsakymo matoma, kad kintamųjų reikšmės buvo apkeistos vietomis
    })
    it('BUILD 8 | SULIPDYMAS 7&4', () => {
        cy.get('#selectBuild').select('8').should('have.value', '8')
        cy.get('#selectBuild').should('have.value', '8')
        cy.get('#selectOperationDropdown').select('4').should('have.value', '4')
        cy.get('#selectOperationDropdown').should('have.value', '4')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '74') //BUG: Kintamųjų reikšmės apkeistos vietomis. Skaičiai sulipdyti atvirkščiai
    })
    it('BUILD 9 | SUDĖTIS 7+4', () => {
        cy.get('#selectBuild').select('9').should('have.value', '9')
        cy.get('#selectBuild').should('have.value', '9')
        cy.get('#selectOperationDropdown').select('0').should('have.value', '0')
        cy.get('#selectOperationDropdown').should('have.value', '0')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '11')
    })
    it('BUILD 9 | ATIMTIS 7-4', () => {
        cy.get('#selectBuild').select('9').should('have.value', '9')
        cy.get('#selectBuild').should('have.value', '9')
        cy.get('#selectOperationDropdown').select('1').should('have.value', '1')
        cy.get('#selectOperationDropdown').should('have.value', '1')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '3')
    })
    it('BUILD 9 | DAUGYBA 7*4', () => {
        let selectBuild = cy.get('#selectBuild')
        selectBuild.select('9').should('have.value', '9')
        selectBuild.should('have.value', '9')
        let selectDropdown = cy.get('#selectOperationDropdown')
        selectDropdown.select('2').should('have.value', '2')
        selectDropdown.should('have.value', '2')

        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '28')
    })
    it('BUILD 9 | DALYBA 7/4', () => {
        cy.get('#selectBuild').select('9').should('have.value', '9')
        cy.get('#selectBuild').should('have.value', '9')
        cy.get('#selectOperationDropdown').select('3').should('have.value', '3')
        cy.get('#selectOperationDropdown').should('have.value', '3')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '1.75')
    })
    it('BUILD 9 | SULIPDYMAS 7&4', () => {
        cy.get('#selectBuild').select('9').should('have.value', '9')
        cy.get('#selectBuild').should('have.value', '9')
        cy.get('#selectOperationDropdown').select('4').should('have.value', '4')
        cy.get('#selectOperationDropdown').should('have.value', '4')
        cy.get('#number1Field').type('7')
        cy.get('#number2Field').type('4')
        cy.get('#calculateButton').click()
        cy.get('#numberAnswerField').should('have.value', '74')
    })
})
